version: '3.8'

services:
  # ==========================================
  # Redis (BullMQ broker + cache)
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: oxy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - oxy-network

  # ==========================================
  # Backend API + Socket.IO
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oxy-backend
    ports:
      - "3001:3001"
    volumes:
      # Persistent WhatsApp sessions
      - ./backend/sessions:/app/sessions
      # Hot reload for development (optional)
      # - ./backend/src:/app/src
      # - ./backend/dist:/app/dist
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - oxy-network

  # ==========================================
  # Background Worker (Message Processor)
  # ==========================================
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oxy-worker
    command: node dist/workers/message-processor.js
    volumes:
      # Share sessions with backend
      - ./backend/sessions:/app/sessions
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - oxy-network

  # ==========================================
  # Frontend (React + Vite) - Optional
  # Uncomment if you want to run frontend locally
  # ==========================================
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: oxy-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/public:/app/public
  #   env_file:
  #     - ./frontend/.env
  #   environment:
  #     - VITE_API_URL=http://localhost:3001
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     - oxy-network

# ==========================================
# Volumes
# ==========================================
volumes:
  redis-data:
    driver: local

# ==========================================
# Networks
# ==========================================
networks:
  oxy-network:
    driver: bridge
